name: DynamicLighting
version: '1.0'
main: lopiktwo.github.dynamicLighting.DynamicLighting
api-version: '1.21'
commands:
  dl:
    description: main command for plugin
permissions:
  dynamiclighting:
    description: Full access
    default: op